import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
import { postgresClient } from "../src/db/client";
import { resolveServicePricing } from "../src/lib/accounting/service-pricing";
import { saveFinancialReviewInTransaction } from "../src/lib/accounting/review";

async function main() {
await postgresClient.begin(async (tx) => {
  const [user] = await tx.unsafe<Array<{id:string}>>("select id from users where username='tests'");
  const hospitals = await tx.unsafe<Array<{id:string}>>("select id from hospitals where archived_at is null order by id limit 2");
  const [equipment] = await tx.unsafe<Array<{id:string}>>("select id from equipment where archived_at is null order by id limit 1");
  const [procedure] = await tx.unsafe<Array<{id:string}>>("select id from procedures where archived_at is null order by id limit 1");
  assert(user && hospitals.length === 2 && equipment && procedure, "required reference fixtures exist");
  const template = async (type:string) => (await tx.unsafe<Array<{id:string}>>("select id from work_form_templates where operation_type=$1::operation_type and status='published'",[type]))[0];
  const contractTemplate=await template("contract"), endoscopyTemplate=await template("endoscopy");
  await tx.unsafe("update service_pricing_profiles set active=false,archived_at=now() where active=true and (operation_type='endoscopy' or hospital_id=any($1::uuid[]))", [hospitals.map((hospital) => hospital.id)]);
  const createProfile=async(type:string,hospitalId:string|null,name:string)=> (await tx.unsafe<Array<{id:string}>>(`insert into service_pricing_profiles(operation_type,hospital_id,name,created_by_user_id,updated_by_user_id) values($1::operation_type,$2::uuid,$3,$4::uuid,$4::uuid) returning id`,[type,hospitalId,name,user.id]))[0];
  const contractA=await createProfile("contract",hospitals[0].id,"TEST-B25-CONTRACT-A"),contractB=await createProfile("contract",hospitals[1].id,"TEST-B25-CONTRACT-B"),endoscopy=await createProfile("endoscopy",null,"TEST-B25-ENDOSCOPY");
  const addPrice=async(profileId:string,key:string,sourceType:string,referenceId:string|null,label:string,amount:number)=>(await tx.unsafe<Array<{id:string}>>(`insert into service_pricing_items(profile_id,stable_key,source_type,source_reference_id,label,default_amount,created_by_user_id,updated_by_user_id) values($1::uuid,$2,$3::financial_item_source_type,$4::uuid,$5,$6,$7::uuid,$7::uuid) returning id`,[profileId,key,sourceType,referenceId,label,amount,user.id]))[0];
  const itemA=await addPrice(contractA.id,`equipment:${equipment.id}`,"equipment",equipment.id,"جهاز تعاقد",2000);
  await addPrice(contractB.id,`equipment:${equipment.id}`,"equipment",equipment.id,"جهاز تعاقد",2500);
  const endoscopyItem=await addPrice(endoscopy.id,`equipment:${equipment.id}`,"equipment",equipment.id,"منظار",2500);
  const createOperation=async(type:"contract"|"endoscopy",hospitalId:string,templateId:string,name:string,sequence:number)=> (await tx.unsafe<Array<{id:string}>>(`insert into operations(type,status,operation_date,daily_sequence,operation_time,case_name,hospital_id,form_template_id,created_by_user_id,updated_by_user_id) values($1::operation_type,'recorded',current_date,$2,'10:00',$3,$4::uuid,$5::uuid,$6::uuid,$6::uuid) returning id`,[type,sequence,name,hospitalId,templateId,user.id]))[0];
  const contractOperation=await createOperation("contract",hospitals[0].id,contractTemplate.id,"TEST-B25-CONTRACT",9101);
  await tx.unsafe("insert into operation_equipment(operation_id,equipment_id) values($1::uuid,$2::uuid)",[contractOperation.id,equipment.id]);
  await tx.unsafe("insert into operation_procedures(operation_id,procedure_id) values($1::uuid,$2::uuid)",[contractOperation.id,procedure.id]);
  const resolvedContract=await resolveServicePricing(contractOperation.id,tx);
  const contractEquipment=resolvedContract.prices.find(price=>price.source?.sourceReferenceId===equipment.id);
  assert.equal(contractEquipment?.defaultAmount,2000,"Hospital A resolves its own item price");
  assert.equal(resolvedContract.profile?.id,contractA.id,"Contract resolves by hospital");
  await assert.rejects(()=>(import("../src/lib/accounting/review")).then(module=>module.getFinancialReviewOperation(contractOperation.id,{id:user.id,permissions:[]} as never,tx)),(error:{status?:number})=>error.status===403,"employee/no-finance principal cannot retrieve financial DTO");
  const secondOperation=await createOperation("contract",hospitals[1].id,contractTemplate.id,"TEST-B25-CONTRACT-B",9102);
  await tx.unsafe("insert into operation_equipment(operation_id,equipment_id) values($1::uuid,$2::uuid)",[secondOperation.id,equipment.id]);
  assert.equal((await resolveServicePricing(secondOperation.id,tx)).prices.find(price=>price.source?.sourceReferenceId===equipment.id)?.defaultAmount,2500,"same catalog item differs by hospital");
  const saveInput=(price:NonNullable<typeof contractEquipment>,amount:number)=>({expectedUpdatedAt:null,accountingMode:"direct_items" as const,mainAmount:null,doctorReceivedAmount:null,doctorAccountAmount:"999999.00",doctorBalanceReceived:false,notes:"contract snapshot",items:[{catalogItemId:null,kind:"financial" as const,financialEffect:price.effect,sourceType:"equipment" as const,sourceFieldId:price.source?.sourceFieldId??null,sourceReferenceId:equipment.id,definitionId:null,pricingProfileId:null,pricingProfileLineId:null,pricingProfileVersion:null,servicePricingProfileId:price.servicePricingProfileId,servicePricingItemId:price.servicePricingItemId,servicePricingVersion:price.servicePricingVersion,baseAmount:String(price.defaultAmount),adjustmentAmount:String(amount-Number(price.defaultAmount)),effectiveAmount:String(amount),caseLineState:"included" as const,description:price.label,amount:String(amount),notes:"case override"}]});
  const financialUser={id:user.id,permissions:["accounting.finance.edit"],role:{code:"owner"}} as never;
  const firstSave=await saveFinancialReviewInTransaction(tx,contractOperation.id,saveInput(contractEquipment!,2300),financialUser);
  const [saved]=await tx.unsafe<Array<{due:number;base:number;effective:number;mode:string}>>(`select fr.doctor_account_amount due,fr.accounting_mode mode,i.base_amount base,i.effective_amount effective from operation_financial_reviews fr join operation_financial_items i on i.review_id=fr.id where fr.operation_id=$1::uuid`,[contractOperation.id]);
  assert.equal(Number(saved.due),2300,"server computes Contract total and ignores forged total");assert.equal(Number(saved.base),2000);assert.equal(Number(saved.effective),2300);assert.equal(saved.mode,"direct_items");
  const excluded={...saveInput(contractEquipment!,2300),expectedUpdatedAt:firstSave.updatedAt,items:[{...saveInput(contractEquipment!,2300).items[0],caseLineState:"excluded" as const}]};
  const excludedSave=await saveFinancialReviewInTransaction(tx,contractOperation.id,excluded,financialUser);
  assert.equal(Number((await tx.unsafe<Array<{due:number}>>("select doctor_account_amount due from operation_financial_reviews where operation_id=$1::uuid",[contractOperation.id]))[0].due),0,"excluded Contract item stops affecting total");
  const restored={...saveInput(contractEquipment!,2300),expectedUpdatedAt:excludedSave.updatedAt};
  await saveFinancialReviewInTransaction(tx,contractOperation.id,restored,financialUser);
  assert.equal(Number((await tx.unsafe<Array<{due:number}>>("select doctor_account_amount due from operation_financial_reviews where operation_id=$1::uuid",[contractOperation.id]))[0].due),2300,"restored Contract item affects total again");
  await tx.unsafe("update service_pricing_items set default_amount=2800 where id=$1::uuid",[itemA.id]);
  const historical=await (await import("../src/lib/accounting/review")).getFinancialReviewOperation(contractOperation.id,{id:user.id,permissions:["accounting.review"]} as never,tx);
  assert.equal(historical.pricingDefaults,null,"saved Contract review is not rehydrated");assert.equal(Number(historical.review.items[0].baseAmount),2000);assert.equal(Number(historical.review.items[0].effectiveAmount),2300);
  const endoscopyOperation=await createOperation("endoscopy",hospitals[0].id,endoscopyTemplate.id,"TEST-B25-ENDOSCOPY",9103);
  await tx.unsafe("insert into operation_equipment(operation_id,equipment_id) values($1::uuid,$2::uuid)",[endoscopyOperation.id,equipment.id]);
  const endoscopyPrice=(await resolveServicePricing(endoscopyOperation.id,tx)).prices.find(price=>price.source?.sourceReferenceId===equipment.id)!;
  assert.equal(endoscopyPrice.defaultAmount,2500,"Endoscopy general default resolves");
  await saveFinancialReviewInTransaction(tx,endoscopyOperation.id,saveInput({...endoscopyPrice,servicePricingItemId:endoscopyItem.id},2300),{id:user.id,permissions:["accounting.finance.edit"],role:{code:"owner"}} as never);
  const [endoscopySaved]=await tx.unsafe<Array<{due:number;base:number}>>(`select fr.doctor_account_amount due,i.base_amount base from operation_financial_reviews fr join operation_financial_items i on i.review_id=fr.id where fr.operation_id=$1::uuid`,[endoscopyOperation.id]);
  assert.equal(Number(endoscopySaved.due),2300);assert.equal(Number(endoscopySaved.base),2500,"case override preserves reference");
  await tx.unsafe("update service_pricing_items set default_amount=3000 where id=$1::uuid",[endoscopyItem.id]);
  const historicalEndoscopy=await (await import("../src/lib/accounting/review")).getFinancialReviewOperation(endoscopyOperation.id,{id:user.id,permissions:["accounting.review"]} as never,tx);
  assert.equal(Number(historicalEndoscopy.review.items[0].baseAmount),2500,"Endoscopy snapshot survives default edit");
  throw new Error("ROLLBACK_B25");
}).catch(error=>{if((error as Error).message!=="ROLLBACK_B25")throw error;});

const service=await readFile("src/lib/operations/service.ts","utf8"),route=await readFile("src/app/api/v1/financial-reviews/service-pricing/[operationType]/route.ts","utf8");
assert.match(service,/o\.type<>'contract'/,"Contract is excluded from doctor posting server-side");
assert.match(service,/CONTRACT_DOCTOR_PAYMENT_FORBIDDEN/,"Contract doctor payment rejected server-side");
assert.match(route,/requirePermission\(servicePricingPermission\(type\)\)/,"pricing routes require domain permission");
console.log("Contract hospital and Endoscopy pricing checks passed with transaction rollback");
await postgresClient.end();
}
main().catch(async(error)=>{console.error(error);await postgresClient.end();process.exitCode=1;});
