"use client";
import { useEffect, useMemo, useRef, useState } from "react";
import { useDialogScrollLock } from "@/components/settings/users/use-dialog-scroll-lock";
import { systemFieldCapability } from "@/lib/work-forms/policy";
import type { FieldType, OperationType, SmartDropdownSource } from "@/lib/work-forms/types";
import type { BuilderField, BuilderSection, BuilderTemplate } from "./work-form-types";

const operationLabels: Record<OperationType,string>={lithotripsy:"التفتيت",endoscopy:"المناظير",contract:"التعاقد"};
const fieldLabels:Record<FieldType,string>={text:"نص قصير",textarea:"نص طويل / ملاحظات",number:"رقم",money:"قيمة مالية",date:"تاريخ",time:"وقت",boolean:"نعم / لا",select:"قائمة اختيارات",smart_single:"قائمة ذكية — اختيار واحد",smart_multi:"قائمة ذكية — اختيارات متعددة"};
const sourceLabels:Record<SmartDropdownSource,string>={doctors:"الأطباء",hospitals:"المستشفيات",procedures:"الإجراءات",equipment:"الأجهزة / المناظير",consumables:"المستلزمات",stents:"الدعامات",anesthesiologists:"أطباء التخدير",technicians:"الفنيون",contract_entities:"جهات التعاقد",anesthesia_types:"أنواع التخدير",users:"مستخدمو النظام"};
type FieldDraft=Omit<BuilderField,"id"|"stableKey"|"sortOrder"|"isSystemField"|"archivedAt">;
const blankField=(sectionId:string):FieldDraft=>({sectionId,label:"",description:null,fieldType:"text",required:false,multiple:false,smartDropdownSource:null,minSelections:null,maxSelections:null,showInForm:true,showInDetails:true,showInFinancialReview:false,showInPrint:false,isFinancial:false,financialEffect:null});

export function WorkFormBuilder({type,onClose,onPreview,onDraftExists,onTypeChange,onPublished}:{type:OperationType;onClose:()=>void;onPreview:(template:BuilderTemplate|null)=>void;onDraftExists:()=>void;onTypeChange:(type:OperationType)=>void;onPublished?:(template:BuilderTemplate)=>void}) {
  const [draft,setDraft]=useState<BuilderTemplate|null>(null),[published,setPublished]=useState<BuilderTemplate|null>(null),[loading,setLoading]=useState(true),[busy,setBusy]=useState(false),[error,setError]=useState(""),[message,setMessage]=useState("");
  const [fieldEditor,setFieldEditor]=useState<{field:BuilderField|null;value:FieldDraft}|null>(null);
  const [sectionEditor,setSectionEditor]=useState<{section:BuilderSection|null;label:string;description:string}|null>(null);
  const [dirty,setDirty]=useState(false);const panel=useRef<HTMLElement>(null);
  useDialogScrollLock(true,false);
  useEffect(()=>{void load()},[type]); // eslint-disable-line react-hooks/exhaustive-deps
  useEffect(()=>{onPreview(draft);return()=>onPreview(null)},[draft,onPreview]);
  useEffect(()=>{const handler=(event:BeforeUnloadEvent)=>{if(dirty){event.preventDefault();event.returnValue=""}};addEventListener("beforeunload",handler);return()=>removeEventListener("beforeunload",handler)},[dirty]);
  useEffect(()=>{panel.current?.focus();const key=(event:KeyboardEvent)=>{if(event.key==="Escape")attemptClose()};document.addEventListener("keydown",key);return()=>document.removeEventListener("keydown",key)});
  async function load(){setLoading(true);setError("");const response=await fetch(`/api/v1/work-forms/${type}/draft`);const data=await response.json();setLoading(false);if(!response.ok){setError(data.error?.message??"تعذر تحميل المسودة");return}setDraft(data.draft);setPublished(data.published);onDraftExists()}
  async function mutate(payload:Record<string,unknown>){if(!draft)return;setBusy(true);setError("");const response=await fetch(`/api/v1/work-forms/${type}/draft`,{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify({...payload,expectedUpdatedAt:draft.updatedAt})});const data=await response.json();setBusy(false);if(!response.ok){setError(data.error?.message??"تعذر حفظ التعديل");if(data.error?.code==="STALE_DRAFT")setMessage("أعد تحميل المسودة قبل المتابعة.");return false}setDraft(data.draft);setDirty(false);setMessage("تم حفظ المسودة.");return true}
  function attemptClose(){if(dirty&&!confirm("لديك تعديلات غير محفوظة. هل تريد تجاهلها؟"))return;onClose()}
  function changeType(next:OperationType){if(next===type)return;if(dirty&&!confirm("لديك تعديلات غير محفوظة. هل تريد تجاهلها؟"))return;setDirty(false);setFieldEditor(null);setSectionEditor(null);setDraft(null);setPublished(null);onPreview(null);onTypeChange(next)}
  async function publish(){if(!draft||!confirm("سيتم اعتماد هذا النموذج للعمليات الجديدة. العمليات القديمة ستظل مرتبطة بإصدارها السابق."))return;setBusy(true);const response=await fetch(`/api/v1/work-forms/${type}/publish`,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({expectedUpdatedAt:draft.updatedAt})});const data=await response.json();setBusy(false);if(!response.ok){setError(data.error?.message??"تعذر نشر النموذج");return}setMessage(`تم نشر الإصدار v${data.published.version}.`);setPublished(data.published);setDraft(null);onPreview(null);onPublished?.(data.published)}
  const sections=useMemo(()=>draft?.sections.filter(section=>!section.archivedAt)??[],[draft]);
  async function moveSection(index:number,delta:number){const next=[...sections];const target=index+delta;if(target<0||target>=next.length)return;[next[index],next[target]]=[next[target],next[index]];await mutate({action:"reorder_sections",sectionIds:next.map(item=>item.id)})}
  async function moveField(section:BuilderSection,index:number,delta:number){const fields=section.fields.filter(field=>!field.archivedAt);const target=index+delta;if(target<0||target>=fields.length)return;[fields[index],fields[target]]=[fields[target],fields[index]];await mutate({action:"reorder_fields",sectionId:section.id,fieldIds:fields.map(item=>item.id)})}
  async function saveSection(){if(!sectionEditor)return;const ok=await mutate(sectionEditor.section?{action:"update_section",sectionId:sectionEditor.section.id,section:{label:sectionEditor.label,description:sectionEditor.description||null}}:{action:"add_section",section:{label:sectionEditor.label,description:sectionEditor.description||null}});if(ok)setSectionEditor(null)}
  async function saveField(){if(!fieldEditor)return;const value={...fieldEditor.value,multiple:fieldEditor.value.fieldType==="smart_multi",smartDropdownSource:fieldEditor.value.fieldType.startsWith("smart_")?fieldEditor.value.smartDropdownSource:null,minSelections:fieldEditor.value.fieldType==="smart_multi"?fieldEditor.value.minSelections:null,maxSelections:fieldEditor.value.fieldType==="smart_multi"?fieldEditor.value.maxSelections:null,financialEffect:fieldEditor.value.isFinancial?(fieldEditor.value.financialEffect??"neutral"):null};const ok=await mutate(fieldEditor.field?{action:"update_field",fieldId:fieldEditor.field.id,field:value}:{action:"add_field",field:value});if(ok)setFieldEditor(null)}
  const previewDraft=useMemo(()=>fieldEditor&&draft?{...draft,sections:draft.sections.map(section=>({...section,fields:section.id===fieldEditor.value.sectionId?[...section.fields.filter(field=>field.id!==fieldEditor.field?.id),{...fieldEditor.value,id:fieldEditor.field?.id??"preview-new",stableKey:fieldEditor.field?.stableKey??"preview",sortOrder:999,isSystemField:false,archivedAt:null}]:section.fields.filter(field=>field.id!==fieldEditor.field?.id)}))}:draft,[draft,fieldEditor]);
  useEffect(()=>{if(fieldEditor&&previewDraft)onPreview(previewDraft)},[fieldEditor,previewDraft,onPreview]);
  return <div className="work-form-builder" role="dialog" aria-modal="true" aria-label={`إعداد نموذج ${operationLabels[type]}`}><button className="work-form-builder__backdrop" aria-label="إغلاق إعدادات النموذج" onClick={attemptClose}/><aside ref={panel} tabIndex={-1}>
    <header><div><span>إعداد نموذج {operationLabels[type]}</span><h2>{draft?.name??"إعدادات النموذج"}</h2><div className="builder-versions"><b>منشور v{published?.version??"—"}</b>{draft&&<b>مسودة v{draft.version}</b>}</div></div><button onClick={attemptClose} aria-label="إغلاق">×</button></header>
    <main><nav className="builder-type-switch" aria-label="اختيار نوع النموذج">{(Object.keys(operationLabels) as OperationType[]).map(item=><button key={item} className={item===type?"active":""} aria-pressed={item===type} onClick={()=>changeType(item)}>{operationLabels[item]}</button>)}</nav>{loading?<p className="builder-state">جاري إنشاء المسودة...</p>:error&&!draft?<p className="builder-state error">{error}</p>:<>
      {message&&<p className="builder-message">{message}</p>}{error&&<p className="builder-state error">{error}</p>}
      {fieldEditor?<FieldEditor type={type} editor={fieldEditor} sections={sections} onChange={value=>{setFieldEditor({...fieldEditor,value});setDirty(true)}} onCancel={()=>{setFieldEditor(null);setDirty(false)}} onSave={()=>void saveField()} busy={busy}/>:sectionEditor?<SectionEditor editor={sectionEditor} onChange={value=>{setSectionEditor(value);setDirty(true)}} onCancel={()=>{setSectionEditor(null);setDirty(false)}} onSave={()=>void saveSection()} busy={busy}/>:<div className="builder-sections">
        {sections.map((section,index)=><article key={section.id}><div className="builder-section__head"><span className="builder-handle">☰</span><div><strong>{section.label}</strong>{section.description&&<small>{section.description}</small>}</div><div className="builder-row-actions"><button onClick={()=>void moveSection(index,-1)} disabled={index===0} aria-label="تحريك القسم لأعلى">↑</button><button onClick={()=>void moveSection(index,1)} disabled={index===sections.length-1} aria-label="تحريك القسم لأسفل">↓</button><button onClick={()=>setSectionEditor({section,label:section.label,description:section.description??""})} aria-label="تعديل القسم">✏</button>{!section.isSystemSection&&<button className="danger" onClick={()=>confirm("سيتم إخفاء القسم وحقوله من هذه المسودة. متابعة؟")&&void mutate({action:"remove_section",sectionId:section.id})}>×</button>}</div></div>
          <div className="builder-fields">{section.fields.filter(field=>!field.archivedAt).map((field,fieldIndex)=><div className="builder-field" key={field.id}><span>☰</span><div><b>{field.label}</b><small>{fieldLabels[field.fieldType]} · {field.required?"إلزامي":"اختياري"}</small></div><div className="builder-row-actions"><button onClick={()=>void moveField(section,fieldIndex,-1)} disabled={fieldIndex===0} aria-label="تحريك الحقل لأعلى">↑</button><button onClick={()=>void moveField(section,fieldIndex,1)} disabled={fieldIndex===section.fields.filter(item=>!item.archivedAt).length-1} aria-label="تحريك الحقل لأسفل">↓</button><button onClick={()=>setFieldEditor({field,value:toDraft(field)})} aria-label="تعديل الحقل">✏</button><button className="danger" onClick={()=>confirm("هل تريد إزالة هذا الحقل من النماذج الجديدة؟")&&void mutate({action:"remove_field",fieldId:field.id})}>×</button></div></div>)}{!section.fields.some(field=>!field.archivedAt)&&<p className="builder-empty">لا توجد حقول في هذا القسم.</p>}<button className="builder-inline-add" onClick={()=>setFieldEditor({field:null,value:blankField(section.id)})}>+ إضافة حقل داخل القسم</button></div>
        </article>)}<button className="builder-add" onClick={()=>setFieldEditor({field:null,value:blankField(sections[0]?.id??"")})}>+ إضافة حقل</button><button className="builder-add" onClick={()=>setSectionEditor({section:null,label:"",description:""})}>+ إضافة قسم</button>
      </div>}</>}</main>
    <footer><button onClick={attemptClose}>إلغاء</button><button disabled={busy||!draft} onClick={()=>{if(fieldEditor){void saveField();return}if(sectionEditor){void saveSection();return}setDirty(false);setMessage("المسودة محفوظة.");}}>حفظ المسودة</button><button className="primary" disabled={busy||!draft||dirty} onClick={()=>void publish()}>حفظ ونشر</button></footer>
  </aside></div>;
}
function toDraft(field:BuilderField):FieldDraft{return {sectionId:field.sectionId,label:field.label,description:field.description,fieldType:field.fieldType,required:field.required,multiple:field.multiple,smartDropdownSource:field.smartDropdownSource,minSelections:field.minSelections,maxSelections:field.maxSelections,showInForm:field.showInForm,showInDetails:field.showInDetails,showInFinancialReview:field.showInFinancialReview,showInPrint:field.showInPrint,isFinancial:field.isFinancial,financialEffect:field.financialEffect}}
function SectionEditor({editor,onChange,onCancel,onSave,busy}:{editor:{section:BuilderSection|null;label:string;description:string};onChange:(value:typeof editor)=>void;onCancel:()=>void;onSave:()=>void;busy:boolean}){return <div className="builder-editor"><h3>{editor.section?"تعديل القسم":"إضافة قسم"}</h3><label>اسم القسم<input autoFocus value={editor.label} onChange={event=>onChange({...editor,label:event.target.value})}/></label><label>وصف اختياري<textarea value={editor.description} onChange={event=>onChange({...editor,description:event.target.value})}/></label><div><button onClick={onCancel}>إلغاء</button><button className="primary" disabled={busy||editor.label.trim().length<2} onClick={onSave}>حفظ</button></div></div>}
function FieldEditor({type,editor,sections,onChange,onCancel,onSave,busy}:{type:OperationType;editor:{field:BuilderField|null;value:FieldDraft};sections:BuilderSection[];onChange:(value:FieldDraft)=>void;onCancel:()=>void;onSave:()=>void;busy:boolean}){const value=editor.value,capability=editor.field?.isSystemField?systemFieldCapability(type,editor.field.stableKey):null;const set=<K extends keyof FieldDraft>(key:K,next:FieldDraft[K])=>onChange({...value,[key]:next});return <div className="builder-editor"><h3>{editor.field?"تعديل الحقل":"إضافة حقل"}</h3>{editor.field?.isSystemField&&<p className="builder-protected">حقل نظام: الهوية والنوع محميان، ويمكن تعديل العرض حيث يسمح النظام.</p>}<label>اسم الحقل<input autoFocus value={value.label} onChange={event=>set("label",event.target.value)}/></label><label>الوصف / المساعدة<textarea value={value.description??""} onChange={event=>set("description",event.target.value||null)}/></label><label>نوع الإدخال<select value={value.fieldType} disabled={Boolean(editor.field?.isSystemField&&!capability?.canChangeType)} onChange={event=>{const fieldType=event.target.value as FieldType;set("fieldType",fieldType);onChange({...value,fieldType,multiple:fieldType==="smart_multi",smartDropdownSource:fieldType.startsWith("smart_")?(value.smartDropdownSource??"doctors"):null})}}>{Object.entries(fieldLabels).map(([code,label])=><option key={code} value={code}>{label}</option>)}</select></label><label>القسم<select value={value.sectionId} onChange={event=>set("sectionId",event.target.value)}>{sections.map(section=><option key={section.id} value={section.id}>{section.label}</option>)}</select></label>
  <fieldset><legend>الإدخال</legend><label><input type="radio" checked={value.required} disabled={Boolean(capability&&!capability.canChangeRequired)} onChange={()=>set("required",true)}/> إلزامي</label><label><input type="radio" checked={!value.required} disabled={Boolean(capability&&!capability.canChangeRequired)} onChange={()=>set("required",false)}/> اختياري</label></fieldset>
  {value.fieldType==="smart_multi"&&<div className="builder-two"><label>الحد الأدنى<input type="number" min="0" value={value.minSelections??0} onChange={event=>set("minSelections",Number(event.target.value))}/></label><label>الحد الأقصى<input type="number" min="0" placeholder="بدون حد" value={value.maxSelections??""} onChange={event=>set("maxSelections",event.target.value?Number(event.target.value):null)}/></label></div>}
  {value.fieldType.startsWith("smart_")&&<label>مصدر البيانات<select value={value.smartDropdownSource??""} disabled={Boolean(editor.field?.isSystemField)} onChange={event=>set("smartDropdownSource",event.target.value as SmartDropdownSource)}><option value="">اختر المصدر</option>{Object.entries(sourceLabels).map(([code,label])=><option value={code} key={code}>{label}</option>)}</select></label>}
  <fieldset><legend>الظهور</legend><label><input type="checkbox" checked={value.showInForm} disabled={Boolean(capability&&!capability.canHideFromForm)} onChange={event=>set("showInForm",event.target.checked)}/> يظهر في فورم العملية</label><label><input type="checkbox" checked={value.showInDetails} onChange={event=>set("showInDetails",event.target.checked)}/> يظهر في التفاصيل</label><label><input type="checkbox" checked={value.showInFinancialReview} onChange={event=>set("showInFinancialReview",event.target.checked)}/> يظهر في مراجعة المحاسب</label><label><input type="checkbox" checked={value.showInPrint} onChange={event=>set("showInPrint",event.target.checked)}/> يظهر في الطباعة</label></fieldset>
  <fieldset><legend>البيانات المالية</legend><label><input type="checkbox" checked={value.isFinancial} onChange={event=>{set("isFinancial",event.target.checked);onChange({...value,isFinancial:event.target.checked,financialEffect:event.target.checked?(value.financialEffect??"neutral"):null})}}/> حقل مالي</label>{value.isFinancial&&<select value={value.financialEffect??"neutral"} onChange={event=>set("financialEffect",event.target.value as FieldDraft["financialEffect"])}><option value="add">إضافة</option><option value="subtract">خصم</option><option value="neutral">بدون تأثير</option></select>}</fieldset><div><button onClick={onCancel}>إلغاء</button><button className="primary" disabled={busy||value.label.trim().length<2||!value.sectionId} onClick={onSave}>حفظ الحقل</button></div></div>}
